### Probabilistic Machine Learning (Book 1)

Kevin P Murphy

#### Exercises, Chapter 6

In [96]:
import pandas as pd
import math
import numpy as np

**Exercise 6.1** [Expressing mutual information in terms of entropies *] 

Prove the following identities:

$I(X;Y) = H(X)−H(X|Y) = H(Y)−H(Y|X)$

and

$H(X,Y) = H(X|Y)+H(Y|X)+I(X;Y)$

Recalling the definition of conditional entropy:

$\mathbb{H}(Y|X) = \mathbb{E}_{p(X)}[\mathbb{H}(p(Y|X))] = \sum_{x \in \mathcal{X}}p(x)\left(-\sum_{y \in \mathcal{Y}}p(y|x)\log p(y|x)\right),$

and the definition of mutual information:

$\mathbb{I}(X; Y) = \sum_{y \in \mathcal{Y}}\sum_{x \in \mathcal{X}}p(x,y)\log \frac{p(x,y)}{p(x)p(y)},$

we see that

$\mathbb{I}(X; Y) = \sum_{y \in \mathcal{Y}}\sum_{x \in \mathcal{X}}p(x,y)\log \frac{p(x,y)}{p(x)} - \sum_{y \in \mathcal{Y}}\sum_{x \in \mathcal{X}}p(x,y)\log p(y)$

$= \sum_{y \in \mathcal{Y}}\sum_{x \in \mathcal{X}}p(x,y)\log p(y|x) - \sum_{y \in \mathcal{Y}}\sum_{x \in \mathcal{X}}p(x,y)\log p(y)$

$= \sum_{y \in \mathcal{Y}}\sum_{x \in \mathcal{X}}p(y|x)p(x)\log p(y|x) - \sum_{y \in \mathcal{Y}}\sum_{x \in \mathcal{X}}p(x,y)\log p(y)$

$= \sum_{x \in \mathcal{X}}p(x)\left(\sum_{y \in \mathcal{Y}}p(y|x)\log p(y|x)\right) - \sum_{y \in \mathcal{Y}}\left(\sum_{x \in \mathcal{X}}p(x,y)\right)\log p(y)$

$= - \mathbb{E}_{p(X)}\left[\mathbb{H}(p(Y|X))\right] - \sum_{y \in \mathcal{Y}}p(y)\log p(y)$

$= -\mathbb{H}(Y|X) + \mathbb{H}(Y),$

as required for the first identity.

The second identity follows from the "Chain Rule for Entropy:"

$\mathbb{H}(X,Y) = \mathbb{H}(X) + \mathbb{H}(Y|X)$

and from the first identity $I(X;Y) = H(X)−H(X|Y)$:

$\mathbb{H}(X,Y) = \mathbb{H}(Y|X) + \mathbb{H}(X)$

$= \mathbb{H}(Y|X) + I(X;Y) + H(X|Y).$

**Exercise 6.2** [Relationship between D(p||q) and χ2 statistic] (Source: [CT91, Q12.2].)

Show that, if $p(x) \approx q(x)$, then 

$\text{KL}(p||q) \approx \frac{1}{2}\chi^2$

where


$\chi^2 = \sum_{x}\frac{(p(x) − q(x))^2}{q(x)}$

Hint: write

$p(x) = \Delta(x) + q(x)$

$\frac{p(x)}{q(x)} = 1 + \frac{\Delta(x)}{q(x)}$

and use the Taylor series expansion for $\log(1 + x):$ 

$\log(1 + x) = x - \frac{x^2}{2} + \frac{x^3}{3} - \frac{x^4}{4} \cdots$

for $−1 \lt x \leq 1.$

The K-L Divergence is defined as:

$\mathbb{KL}(p||q) = \sum_{x}p(x)\log\frac{p(x)}{q(x)}.$

We have 

$p(x) = \Delta(x) + q(x),$

where it is understood that $\Delta(x)$ is small, i.e., that $p(x)$ and $q(x)$ are "close."

We immediately have that 

$\frac{p(x)}{q(x)} = 1 + \frac{\Delta(x)}{q(x)},$

so that we can write the K-L Diveregence as:

$\mathbb{KL}(p||q) = \sum_{x}(\Delta(x) + q(x))\log(1 + \frac{\Delta(x)}{q(x)}),$

keeping only up to the quadratic term in the T.S. expansion of $\log(1+x),$

$\mathbb{KL}(p||q) = \sum_{x}(\Delta(x) + q(x))(\frac{\Delta(x)}{q(x)} - \frac{1}{2}\frac{\Delta^2(x)}{q^2(x)})$

$=\sum_x \frac{1}{q(x)}\left(\Delta^2(x) - \frac{1}{2}\Delta^2(x) + q(x)\Delta(x) - \frac{1}{2}\frac{\Delta^3(x)}{q(x)} \right) \approx \sum_x \frac{1}{q(x)}\left(\frac{\Delta^2(x)}{2}\right),$

where we have assumed $\frac{\Delta^3(x)}{q(x)} \approx 0,$ and that

$\Delta(x)q(x) = p(x)q(x) - q(x)^2 \approx q(x)^2 - q(x)^2 = 0.$

Hence

$\mathbb{KL}(p||q) \approx \frac{1}{2} \sum_x \frac{1}{q(x)}\Delta^2(x) = \frac{1}{2} \sum_x \frac{(p(x)-q(x))^2}{q(x)} = \frac{1}{2}\chi^2.$

**Exercise 6.3** [Fun with entropies *]
(Source: Mackay.) 

Consider the joint distribution $p(X, Y)$ 

                 x
           1    2    3    4
       1  1/8  1/16  1/32  1/32
     y 2  1/16 1/8   1/32  1/32
       3  1/16 1/16  1/16  1/16
       4  1/4   0     0     0
    
a. What is the joint entropy $H (X, Y )$?

b. What are the marginal entropies $H(X)$ and $H(Y )$?

c. The entropy of $X$ conditioned on a specific value of $y$ is defined as 

$H(X|Y=y)=-\sum_x p(x|y)\log_2 p(x|y)$

Compute $H(X|y)$ for each value of $y$. Does the posterior entropy on $X$ ever increase given an observation of $Y$?

d. The conditional entropy is defined as

$H(X|Y ) = \sum_y p(y)H(X|Y = y)$

Compute this. Does the posterior entropy on $X$ increase or decrease when averaged over the possible values of $Y$ ?

e. What is the mutual information between $X$ and $Y$?

In [4]:
df = pd.DataFrame({'X=1': [1/8, 1/16, 1/16, 1/4],
                   'X=2': [1/16, 1/8, 1/16, 0],
                   'X=3': [1/32, 1/32, 1/16, 0],
                   'X=4': [1/32, 1/32, 1/16, 0],},
                 index=['Y=1', 'Y=2', 'Y=3', 'Y=4'])

a.

The joint entropy $H(X,Y)$ is given by:

$H(X, Y) = - \sum_{x, y}p(x, y)\log_2 p(x, y)$

In [14]:
H = 0
mat = df.values
for ii in range(mat.shape[0]):
    for ij in range(mat.shape[1]):
        if mat[ii, ij] > 0:
            H += - mat[ii, ij]*math.log(mat[ii, ij], 2)
        
print(f"The joint entropy H(X, Y) = {H:.4f} bits")

The joint entropy H(X, Y) = 3.3750 bits


b.

The marginal entropy $H(X)$ is given by

$H(X) = - \sum_{x}p(x) \log_2 p(x),$

where

$p(x=X) = \sum_{y} p(x=X, y).$

In [22]:
pX = df.sum(axis=0)
pY = df.sum(axis=1)

In [23]:
print(pX)
print(pY)

X=1    0.500
X=2    0.250
X=3    0.125
X=4    0.125
dtype: float64
Y=1    0.25
Y=2    0.25
Y=3    0.25
Y=4    0.25
dtype: float64


In [24]:
HX = 0
for px in pX.values:
    if px > 0:
        HX += - px * math.log(px, 2)
HY = 0
for py in pY.values:
    if py > 0:
        HY += - py * math.log(py, 2)
        
print(f"The marginal entropy H(X) = {HX:.4f} bits")
print(f"The marginal entropy H(Y) = {HY:.4f} bits")

The marginal entropy H(X) = 1.7500 bits
The marginal entropy H(Y) = 2.0000 bits


c.

We calculate the conditional probabilitites $p(X|Y=y)$ using $p(X|Y=y) = \frac{p(X,Y)}{P(Y=y)}$:

In [32]:
pXcondY = df.values / pY.values

In [34]:
pXcondY # rows correspond to y = 1, 2, 3, 4

array([[0.5  , 0.25 , 0.125, 0.125],
       [0.25 , 0.5  , 0.125, 0.125],
       [0.25 , 0.25 , 0.25 , 0.25 ],
       [1.   , 0.   , 0.   , 0.   ]])

In [36]:
for ii in range(4):
    y = ii+1
    H = 0
    for ij in range(4):
        if pXcondY[ii, ij] > 0:
            H += -pXcondY[ii, ij] * math.log(pXcondY[ii, ij], 2)
    print(f"H(X|Y={y}) = {H:.4f}")

H(X|Y=1) = 1.7500
H(X|Y=2) = 1.7500
H(X|Y=3) = 2.0000
H(X|Y=4) = 0.0000


The marginal entropy for $X,$ calculated above as $H(X) = 1.75$ increases to a posterior entropy $H(X|Y=3) = 2.0$ after an observation of $Y = 3.$  This is because the distribution $p(X|Y=3)$ is uniform.  Conversely, the posterior entropy $H(X|Y=4) = 0,$ since $p(X|Y=4)$ is degenerate (all its mass is on $X=1$).

d. 

The conditional entropy $H(X|Y)$ (note that this is different to the posterior entropy for $X$ after an observation of a specific value of $Y$ calculated in part c; it is the expectation of the posterior entropy over $Y$) is computed as:

In [37]:
pY

Y=1    0.25
Y=2    0.25
Y=3    0.25
Y=4    0.25
dtype: float64

In [38]:
H = 0
for ii in range(4): # loop over p(Y)
    H_ = 0
    for ij in range(4): # loop over p(X)
        if pXcondY[ii, ij] > 0:
            H_ += -pXcondY[ii, ij] * math.log(pXcondY[ii, ij], 2)
    H += pY[ii] * H_
print(f"H(X|Y) = {H:.4f}")

H(X|Y) = 1.3750


The conditional entropy $H(X|Y)$ is reduced from the marginal entropy $H(X).$  For a specific observation of $Y,$ we may find the posterior entropy increase, but for the conditional entropy, defined as the average posterior entropy over all states of $Y,$ the conditional entropy can only decrease with respect to the marginal value.

e.

The mutual information between $X$ and $Y$ can be calculated in three different ways using the quantities calculated above:

* The difference between the marginal and conditional entropies for either variable
* The difference between the joint entropy and the sum of the conditional entropies
* The difference between the sum of the marginal entropies and the joint entropy

In order to verify the computation using all three methods, we first calculate the conditional entropy $H(Y|X)$ using the same approach as that used to compute $p(X|Y).$

In [57]:
pYcondX = df.values / pX.values

H = 0
for ij in range(4): # loop over p(X) (columns)
    H_ = 0
    for ii in range(4): # loop over p(Y) (rows)
        if pYcondX[ii, ij] > 0:
            H_ += -pYcondX[ii, ij] * math.log(pYcondX[ii, ij], 2)
    H += pX[ij] * H_
print(f"H(Y|X) = {H:.4f}")

H(Y|X) = 1.6250


In [56]:
pYcondX

array([[0.25 , 0.25 , 0.25 , 0.25 ],
       [0.125, 0.5  , 0.25 , 0.25 ],
       [0.125, 0.25 , 0.5  , 0.5  ],
       [0.5  , 0.   , 0.   , 0.   ]])

In [61]:
print(f"I(X;Y) = {(1.75 - 1.375):.4f}\t\t(H(X) - H(X|Y))")
print(f"I(X;Y) = {(2.00 - 1.625):.4f}\t\t(H(Y) - H(Y|X))")
print(f"I(X;Y) = {(3.375 - (1.375 + 1.625)):.4f}\t\t(H(X, Y) - (H(X|Y) + H(Y|X))")
print(f"I(X;Y) = {(1.75 + 2.00 - 3.375):.4f}\t\t(H(X) + H(Y) - H(X,Y))")

I(X;Y) = 0.3750		(H(X) - H(X|Y))
I(X;Y) = 0.3750		(H(Y) - H(Y|X))
I(X;Y) = 0.3750		(H(X, Y) - (H(X|Y) + H(Y|X))
I(X;Y) = 0.3750		(H(X) + H(Y) - H(X,Y))


**Exercise 6.4** [Forwards vs reverse KL divergence]
(Source: Exercise 33.7 of [Mac03].) 

Consider a factored approximation $q(x, y) = q(x)q(y)$ to a joint distribution $p(x, y)$. Show that to minimize the forwards KL $\mathbb{KL}(p||q)$ we should set $q(x) = p(x)$ and $q(y) = p(y)$, i.e., the optimal approximation is a product of marginals.

Now consider the following joint distribution, where the rows represent $y$ and the columns $x$. 

           1   2   3   4
        1 1/8 1/8  0   0
        2 1/8 1/8  0   0
        3  0   0  1/4  0
        4  0   0   0  1/4

Show that the reverse KL $\mathbb{KL}(q||p)$ for this $p$ has three distinct minima. Identify those minima and evaluate $\mathbb{KL}(q||p)$ at each of them. What is the value of $\mathbb{KL}(q||p)$ if we set $q(x, y) = p(x)p(y)$?

We have 

$\mathbb{KL}(p(x, y)||q(x)q(y)) = \sum_{x \in \mathcal{X}} \sum_{y \in \mathcal{Y}} p(x, y) \log \frac{p(x, y)}{q(x)q(y)}$

$= \sum_{x \in \mathcal{X}} \sum_{y \in \mathcal{Y}} p(x, y) \log p(x, y) - 
   \sum_{x \in \mathcal{X}} \sum_{y \in \mathcal{Y}} p(x, y) \log q(x) - 
   \sum_{x \in \mathcal{X}} \sum_{y \in \mathcal{Y}} p(x, y) \log q(y),$
   
where the first term is unaffected by the choice of $q(x), q(y)$, and the second and third terms, are maximized respectively by:

$q^*(x) = \text{argmax}_{q(x)}\sum_{x \in \mathcal{X}} \left[\sum_{y \in \mathcal{Y}} p(x, y)\right] \log q(x) = \text{argmax}_{q(x)}\mathbb{E}[\log q(x)] = p(x),$

$q^*(y) = \text{argmax}_{q(y)}\sum_{y \in \mathcal{Y}} \left[\sum_{x \in \mathcal{X}} p(x, y)\right] \log q(y) = \text{argmax}_{q(y)}\mathbb{E}[\log q(y)] = p(y).$

Hence choosing $q(x), q(y)$ to be the marginals associated with the joint distribution $p(x, y)$ will lead to the lowest possible K-L divergence.

In [130]:
pxy = pd.DataFrame({'X=1':[1/8, 1/8, 0, 0],
                    'X=2':[1/8, 1/8, 0, 0],
                    'X=3':[0,   0, 1/4, 0],
                    'X=4':[0,   0,   0, 1/4]}, 
                  index = ['Y=1', 'Y=2', 'Y=3', 'Y=4'])

In [131]:
pxy

X=1    X=2   X=3   X=4
Y=1  0.125  0.125  0.00  0.00
Y=2  0.125  0.125  0.00  0.00
Y=3  0.000  0.000  0.25  0.00
Y=4  0.000  0.000  0.00  0.25

We know that the reverse K-L:

$\mathbb{KL}(q||p) = \int q(x)\log \frac{q(x)}{p(x)} dx \text{    (continuous version)},$

when minimized, will exclude all areas of the space for which $p$ is zero.

We will then expect to see three minima in the K-L divergence, two of which being degenerate (with all the probability mass at $X = Y = 3$ and $X = Y = 4,$ respectively), and one being non-degenerate but having having mass evenly distributed on $X \in \{1, 2\}$ and $Y \in \{1, 2\}.$

In [187]:
def reverse_KL(p_xy, q_xy):
    """
    Calculate the reverse K-L divergence for a 
    given joint target distribution df p_xy and 
    approximate distribution df q_xy
    """
    assert p_xy.sum().sum() == 1
    assert q_xy.sum().sum() == 1
    pxy = p_xy.values
    qxy = q_xy.values
    assert pxy.shape == qxy.shape
    KL = 0
    for ii in range(pxy.shape[0]):
        for ij in range(pxy.shape[1]):
            if pxy[ii, ij] > 0 and qxy[ii, ij] > 0:
                KL += qxy[ii, ij] * math.log(qxy[ii, ij]/pxy[ii, ij], 2)
            elif pxy[ii, ij] == 0 and qxy[ii, ij] > 0: # denominator = 0
                KL += math.inf
    return KL

In [192]:
# q = p would give us zero K-L Divergence:
reverse_KL(pxy, pxy)

0.0

Degenerate minimum #1: 

In [193]:
qxy = pd.DataFrame({'X=1':[0,   0,   0, 0],
                    'X=2':[0,   0,   0, 0],
                    'X=3':[0,   0,   0, 0],
                    'X=4':[0,   0,   0, 1]}, 
                  index = ['Y=1', 'Y=2', 'Y=3', 'Y=4'])
reverse_KL(pxy, qxy)

2.0

Degenerate minimum #2: 

In [194]:
qxy = pd.DataFrame({'X=1':[0,   0,   0, 0],
                    'X=2':[0,   0,   0, 0],
                    'X=3':[0,   0,   1, 0],
                    'X=4':[0,   0,   0, 0]}, 
                  index = ['Y=1', 'Y=2', 'Y=3', 'Y=4'])
reverse_KL(pxy, qxy)

2.0

Non-degenerate minimum: 

In [195]:
qxy = pd.DataFrame({'X=1':[1/4, 1/4, 0, 0],
                    'X=2':[1/4, 1/4, 0, 0],
                    'X=3':[0,   0,   0, 0],
                    'X=4':[0,   0,   0, 0]}, 
                  index = ['Y=1', 'Y=2', 'Y=3', 'Y=4'])
reverse_KL(pxy, qxy)

1.0

In [171]:
qxy = pd.DataFrame({'X=1':[0,   0,   0, 0],
                    'X=2':[0,   0,   0, 0],
                    'X=3':[0,   0,   0.5, 0],
                    'X=4':[0,   0,   0, 0.5]}, 
                  index = ['Y=1', 'Y=2', 'Y=3', 'Y=4'])
reverse_KL(pxy, qxy)

1.0

The K-L Divergence can be lowered from these minima by joint distributions that cover additional non-zero regions of the target distribution:

In [197]:
qxy = pd.DataFrame({'X=1':[1/12,   1/12,    0,   0],
                    'X=2':[1/12,   1/12,    0,   0],
                    'X=3':[0,         0,  1/3,   0],
                    'X=4':[0,         0,    0, 1/3]}, 
                  index = ['Y=1', 'Y=2', 'Y=3', 'Y=4'])
reverse_KL(pxy, qxy)

0.08170416594551039

However such distributions will often be difficult to identify in real applications.

In this case setting $q(x,y)$ to be the product of the marginals $p(x)p(y)$ will lead to infinite K-L divergence, as $q(x, y)$ will have mass in regions of probability-space where $p(x, y)$ does not:

In [213]:
pX = pxy.sum(axis=0).values
pY = pxy.sum(axis=1).values

In [214]:
print(pX)
print(pY)

[0.25 0.25 0.25 0.25]
[0.25 0.25 0.25 0.25]


In [215]:
qXY = pd.DataFrame(pX.reshape(1, 4) * pY.reshape(4, 1),
                  columns=['X=1', 'X=2', 'X=3', 'X=4'],
                  index=['Y=1', 'Y=2', 'Y=3', 'Y=4'])

In [216]:
qXY # product of the marginals leads to a uniform dictribution

X=1     X=2     X=3     X=4
Y=1  0.0625  0.0625  0.0625  0.0625
Y=2  0.0625  0.0625  0.0625  0.0625
Y=3  0.0625  0.0625  0.0625  0.0625
Y=4  0.0625  0.0625  0.0625  0.0625

In [212]:
reverse_KL(pxy, qXY)

inf